/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as MedicationRouteImport } from './routes/medication'
import { Route as PointAskRouteImport } from './routes/point-ask'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as FamilyMedicationRouteImport } from './routes/family.medication'
import { Route as FamilyMemoryRouteImport } from './routes/family.memory'
import { Route as FamilyNoteRouteImport } from './routes/family.note'
import { Route as FamilySettingsRouteImport } from './routes/family.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationRoute = MedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const PointAskRoute = PointAskRouteImport.update({
  id: '/point-ask',
  path: '/point-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyMedicationRoute = FamilyMedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyMemoryRoute = FamilyMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyNoteRoute = FamilyNoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilySettingsRoute = FamilySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FamilyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/family': typeof FamilyRouteWithChildren
  '/medication': typeof MedicationRoute
  '/point-ask': typeof PointAskRoute
  '/family/medication': typeof FamilyMedicationRoute
  '/family/memory': typeof FamilyMemoryRoute
  '/family/note': typeof FamilyNoteRoute
  '/family/settings': typeof FamilySettingsRoute
  '/family/': typeof FamilyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/medication': typeof MedicationRoute
  '/point-ask': typeof PointAskRoute
  '/family/medication': typeof FamilyMedicationRoute
  '/family/memory': typeof FamilyMemoryRoute
  '/family/note': typeof FamilyNoteRoute
  '/family/settings': typeof FamilySettingsRoute
  '/family': typeof FamilyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/family': typeof FamilyRouteWithChildren
  '/medication': typeof MedicationRoute
  '/point-ask': typeof PointAskRoute
  '/family/medication': typeof FamilyMedicationRoute
  '/family/memory': typeof FamilyMemoryRoute
  '/family/note': typeof FamilyNoteRoute
  '/family/settings': typeof FamilySettingsRoute
  '/family/': typeof FamilyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/family'
    | '/medication'
    | '/point-ask'
    | '/family/medication'
    | '/family/memory'
    | '/family/note'
    | '/family/settings'
    | '/family/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/medication'
    | '/point-ask'
    | '/family/medication'
    | '/family/memory'
    | '/family/note'
    | '/family/settings'
    | '/family'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/family'
    | '/medication'
    | '/point-ask'
    | '/family/medication'
    | '/family/memory'
    | '/family/note'
    | '/family/settings'
    | '/family/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  MedicationRoute: typeof MedicationRoute
  PointAskRoute: typeof PointAskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication': {
      id: '/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof MedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/point-ask': {
      id: '/point-ask'
      path: '/point-ask'
      fullPath: '/point-ask'
      preLoaderRoute: typeof PointAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/': {
      id: '/family/'
      path: '/'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/medication': {
      id: '/family/medication'
      path: '/medication'
      fullPath: '/family/medication'
      preLoaderRoute: typeof FamilyMedicationRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/memory': {
      id: '/family/memory'
      path: '/memory'
      fullPath: '/family/memory'
      preLoaderRoute: typeof FamilyMemoryRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/note': {
      id: '/family/note'
      path: '/note'
      fullPath: '/family/note'
      preLoaderRoute: typeof FamilyNoteRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/settings': {
      id: '/family/settings'
      path: '/settings'
      fullPath: '/family/settings'
      preLoaderRoute: typeof FamilySettingsRouteImport
      parentRoute: typeof FamilyRoute
    }
  }
}

interface FamilyRouteChildren {
  FamilyMedicationRoute: typeof FamilyMedicationRoute
  FamilyMemoryRoute: typeof FamilyMemoryRoute
  FamilyNoteRoute: typeof FamilyNoteRoute
  FamilySettingsRoute: typeof FamilySettingsRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyMedicationRoute: FamilyMedicationRoute,
  FamilyMemoryRoute: FamilyMemoryRoute,
  FamilyNoteRoute: FamilyNoteRoute,
  FamilySettingsRoute: FamilySettingsRoute,
  FamilyIndexRoute: FamilyIndexRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FamilyRoute: FamilyRouteWithChildren,
  MedicationRoute: MedicationRoute,
  PointAskRoute: PointAskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
